[package]
name = "rust-raknet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
rand = {version = "0.8.5", features = ["std"]}
tokio = {version = "1.17.0", features = ["full"]}